package org.alvas.autogeneratedid;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;

public class EmployeeController {
	public static void main(String[] args) {
		EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("ansari");
		EntityManager entityManager = entityManagerFactory.createEntityManager();
		EntityTransaction entityTransaction = entityManager.getTransaction();
		Employee employee = new Employee();
//		employee.setId(300);
		employee.setEmail("putt2gmail.com");
		employee.setName("puttarajbm");
		entityTransaction.begin();
		entityManager.persist(employee);
		entityTransaction.commit(); 
	}
}
